version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:12"
      - image: "mongo:3.4.4"
    steps:
      - checkout
      - run:
          name: "update-npm"
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
      - run:
          name: "install-npm"
          command: "npm install"
      - save_cache:
          paths:
            - "./node_modules"
          key: 'dependency-cache-{{ checksum "package.json" }}'
      - run:
          name: "test"
          command: "npm test"
      - persist_to_workspace:
          root: "/home/circleci"
          paths:
            - "project"
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: "/tmp/workspace"
      - add_ssh_keys
      - run:
          name: "Deploy over SSH"
          command: |
            rsync -rb /tmp/workspace/project/* $SSH_USER@$SSH_HOST:/Users/f19team04/.
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - "build"
          filters:
            branches:
              only: "master"
